services:
  plantuml:
    image: plantuml/plantuml-server:jetty
    container_name: plantuml-server
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - SERVER_PORT=8080
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:8080 > /dev/null 2>&1 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  postgres:
    image: postgres:17.6-alpine3.22
    container_name: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER=rd_user
      - POSTGRES_PASSWORD=rd_pass
      - POSTGRES_DB=rd_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U rd_user -d rd_db || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  rabbitmq:
    image: rabbitmq:3.13.7-alpine
    container_name: rabbitmq
    restart: unless-stopped
    environment:
      - RABBITMQ_DEFAULT_USER=rduser
      - RABBITMQ_DEFAULT_PASS=rdpass
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD-SHELL", "rabbitmq-diagnostics -q ping || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  # Exemplo: se algum serviço depender de Postgres ou RabbitMQ saudáveis
  # my_service:
  #   image: alpine
  #   command: ["sh", "-c", "echo services up"]
  #   depends_on:
  #     postgres:
  #       condition: service_healthy
  #     rabbitmq:
  #       condition: service_healthy

volumes:
  db_data:
  rabbitmq_data: